AssignmentGit/force-app/main/default/objects/Account/fields/Email_Account__c.field-meta.xml
<CustomField>
    <fullName>Email_Account__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Account</label>
    <type>Email</type>
</CustomField>

AssignmentGit/force-app/main/default/objects/Personal_Detail__c/Personal_Detail__c.object-meta.xml
<CustomObject>
    <label>Personal Detail</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AssignmentGit/force-app/main/default/objects/Personal_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Personal Details</relationshipLabel>
    <relationshipName>Personal_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

AssignmentGit/force-app/main/default/objects/Personal_Detail__c/fields/Person_Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Person_Employee_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Person Employee ID</label>
    <type>TextArea</type>
</CustomField>

AssignmentGit/force-app/main/default/classes/triggerHandler.cls
public class triggerHandler {
    public static void UpdateField(List<Account > acc){
        List<Personal_Detail__c> pdlist=new List<Personal_Detail__c>();
        for(Account a:acc){
             Personal_Detail__c pd=new Personal_Detail__c();
            pd.Account__c=a.id;
           
            pd.Name=a.Name;
            pd.Person_Employee_ID__c=a.Id;
            pd.Person_Phone__c=a.Phone;
            pd.Description__c=a.Description;
            pd.Person_Email__c=a.Email_Account__c;
            pdlist.add(pd);
           
        }
        Insert pdlist;
        
}
}