AssignmentGit/force-app/main/default/objects/Account/fields/Email_Account__c.field-meta.xml
<CustomField>
    <fullName>Email_Account__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Account</label>
    <type>Email</type>
</CustomField>

AssignmentGit/force-app/main/default/objects/Personal_Detail__c/Personal_Detail__c.object-meta.xml
<CustomObject>
    <label>Personal Detail</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AssignmentGit/force-app/main/default/objects/Personal_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Personal Details</relationshipLabel>
    <relationshipName>Personal_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

AssignmentGit/force-app/main/default/classes/triggerHandler2.cls
public class triggerHandler2 {
    public static void updateCheck(List<Account> newAccounts, Map<Id, Account> oldAccountMap) {
        List<Personal_Detail__c> personalDetailsToUpdate = new List<Personal_Detail__c>();
        
        for (Account acc : newAccounts) {
            Personal_Detail__c pd=new Personal_Detail__c();
            Account oldAcc = oldAccountMap.get(acc.Id);
           
            if (acc.Email_Account__c != oldAcc.Email_Account__c) {
               
                List<Personal_Detail__c> personalDetails = [SELECT Id, Description__c FROM Personal_Detail__c WHERE Account__c = :acc.Id];
                pd.Description__c = 'Email is Updated from '+oldAcc.Email_Account__c+'to'+acc.Email_Account__c;}
            if(acc.Phone != oldAcc.Phone)     
            { List<Personal_Detail__c> personalDetails1 = [SELECT Id, Description__c FROM Personal_Detail__c WHERE Account__c = :acc.Id];
                pd.Description__c = 'Phone is Updated from '+oldAcc.Phone+'to'+acc.Phone;
                    personalDetailsToUpdate.add(pd);
                }
            }
        
        
            update personalDetailsToUpdate;
        
}
}