AssignmentGit/force-app/main/default/objects/DeveloperP__c/DeveloperP__c.object-meta.xml
<CustomObject>
    <label>DeveloperP</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DeveloperPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AssignmentGit/force-app/main/default/objects/Log__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

AssignmentGit/force-app/main/default/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>StackTrace</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

AssignmentGit/force-app/main/default/classes/DeveloperTriggerHandler.cls
public class DeveloperTriggerHandler {

  public static void handleTrigger(List<DeveloperP__c> developers) {
        List<Log__c> logsToUpdate = new List<Log__c>();
        
        for (DeveloperP__c dev : developers) {
           
            if (!Schema.sObjectType.DeveloperP__c.fields.Salary__c.isUpdateable()) {
      
                Log__c log = new Log__c();
              
                log.Reason__c = 'Salary field does not have update permission.';
                log.StackTrace__c = 'Trigger: DeveloperTrigger, Handler: DeveloperTriggerHandler';
                logsToUpdate.add(log);
            }
        }
        
        if (!logsToUpdate.isEmpty()) {
            insert logsToUpdate;
        }
    }
}